# Generated by Django 5.2.1 on 2025-08-07 19:26

import storages.backends.azure_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourghanaapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("highlight", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("cta_text", models.CharField(max_length=50)),
                ("cta_link", models.CharField(blank=True, max_length=200)),
                (
                    "image",
                    models.ImageField(
                        storage=storages.backends.azure_storage.AzureStorage(),
                        upload_to="slides/",
                    ),
                ),
                ("alt", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.azure_storage.AzureStorage(),
                upload_to="blog_images/",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                storage=storages.backends.azure_storage.AzureStorage(),
                upload_to="gallery_images/",
            ),
        ),
    ]
