name: Django CD Pipeline

on:
  workflow_run:
    workflows: ["Django CI Pipeline"]
    types:
      - completed

jobs:
  deploy-to-azure:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_REPO: joshua192/nasaftours
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Download IMAGE_TAG artifact
        uses: actions/download-artifact@v4
        with:
          name: image_tag
          path: .
      
      - name: Load IMAGE_TAG into env
        run: echo "IMAGE_TAG=$(cat image_tag.txt)" >> $GITHUB_ENV

      - name: Prepare production compose file
        run: |
          mkdir -p deployment
          sed -e "s|build: .|image: ${{ env.DOCKER_HUB_REPO }}:${{ env.IMAGE_TAG }}|" \
              -e "s/container_name: nasaftours_web//" \
              compose.yml > deployment/docker-compose.prod.yml

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Setup .env & required directories on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOT'
          set -e

          APP_DIR=~/nasaftours
          sudo mkdir -p $APP_DIR
          sudo chown -R $USER:$USER $APP_DIR

          tee $APP_DIR/.env > /dev/null <<EOF
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST=db
          DATABASE_PORT=5432
          DATABASE_ENGINE=postgresql
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_LOGLEVEL=info
          DJANGO_ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
          DEBUG=False
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
          AZURE_ACCOUNT_NAME=${{ secrets.AZURE_ACCOUNT_NAME }}
          AZURE_ACCOUNT_KEY=${{ secrets.AZURE_ACCOUNT_KEY }}
          AZURE_MEDIA_CONTAINER=media
          AZURE_CUSTOM_DOMAIN=${{ secrets.AZURE_CUSTOM_DOMAIN }}
          EOF

          sudo mkdir -p /app/logs /app/staticfiles
          sudo chown -R 1000:1000 /app/logs /app/staticfiles
          EOT

      - name: Copy compose file & deploy
        run: |
          scp -o StrictHostKeyChecking=no deployment/docker-compose.prod.yml \
              ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:~/nasaftours/

          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOT'
          set -e

          cd ~/nasaftours

          CURRENT_TAG=$(sudo docker compose -f docker-compose.prod.yml config | grep image | awk '{print $2}' | cut -d':' -f2 || echo "none")
          echo $CURRENT_TAG > previous_tag.txt

          sudo docker compose -f docker-compose.prod.yml down
          sudo docker compose -f docker-compose.prod.yml pull
          sudo docker compose -f docker-compose.prod.yml up -d

          for i in {1..10}; do
              if curl --fail http://localhost:8000/health; then
                  echo "Django is healthy"
                  break
              fi
              echo "Waiting for Django to be ready... ($i/10)"
              sleep 5
          done

          sudo docker compose -f docker-compose.prod.yml exec django-web python manage.py migrate
          sudo docker compose -f docker-compose.prod.yml exec django-web python manage.py collectstatic --noinput

          if ! curl --fail http://localhost:8000/health; then
              echo "Deployment failed, rolling back..."
              if [ -f previous_tag.txt ] && [ "$CURRENT_TAG" != "none" ]; then
                  sudo sed -i "s|:${IMAGE_TAG}|:${CURRENT_TAG}|" docker-compose.prod.yml
                  sudo docker compose -f docker-compose.prod.yml up -d
              fi
              exit 1
          fi

          sudo docker compose -f docker-compose.prod.yml restart django-web
          sudo docker image prune -f
          EOT
